# Generated by Django 3.1.4 on 2021-11-27 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20211127_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='payee_acc',
            new_name='payee_account',
        ),
    ]
