# Generated by Django 3.1.4 on 2021-11-27 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20211127_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='payee_account',
            new_name='payeeAccount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='customer',
            new_name='userAccount',
        ),
    ]
