# Generated by Django 3.1.4 on 2021-11-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_auto_20211127_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='mobile_no',
            field=models.CharField(max_length=11),
        ),
    ]
