# Generated by Django 3.1.4 on 2021-11-30 15:10

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20211130_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='mobile_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
