# Generated by Django 3.1.4 on 2021-11-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_auto_20211130_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
