# Generated by Django 3.1.4 on 2021-12-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_auto_20211130_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payeeAccount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transfer_type',
            field=models.CharField(choices=[('IMPS', 'IMPS'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS')], default='IMPS', max_length=20),
        ),
    ]
