# Generated by Django 3.1.4 on 2022-02-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_auto_20211201_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='otp',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
